### ISSUE TITLE
¿Para qué lo necesitas? Resetea los cambios

### ISSUE THREAD

**Issue by lmagarin** [RafaSojo/Buscaminas-javascript#16]
https://github.com/RafaSojo/Buscaminas-javascript/blob/9c51b2fd17f71a05c6797c0bc62bce89a59839d4/js/buscaminas.js#L163

**Comment by RafaSojo** [comment]
Es la función que se utiliza desde la interfaz gráfica para obtener los cambios. Los cambios se resetean cada vez que se llama a esta función.
